import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FooterClient, Navbar } from "@/components";
import { Toaster } from "react-hot-toast";
import { CartContextProvider } from "@/contexts/cartContext";
import { SessionProvider } from "@/components/providers/SessionProvider";
import { NoSSR } from "@/components/shared/NoSSR";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        
        <SessionProvider>
          <CartContextProvider>
            <Navbar />
            {children}
          </CartContextProvider>
        </SessionProvider>
        <NoSSR>
          <FooterClient />
          <Toaster />
        </NoSSR>
      </body>
    </html>
  );
}
